name: CI / CD

on:
  push:
    branches: [main]
#    paths:
 #     - 'api/**'
 
env:
  REGISTRY: "registry.digitalocean.com/develop-project"
  IMAGE_NAME: "api"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
      working-directory: ./api
      env:
        CI: true

  build_and_push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2
      
    - name: Build container image
      run: docker build -t api-pre .
      working-directory: ./api

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
      
    - name: Tag image 
      run: docker tag $(echo $IMAGE_NAME) $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
      working-directory: ./api

    - name: Push image to DigitalOcean Container Registry
      run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
      working-directory: ./api

  # deploy:
  #   needs: [build_and_push]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: SSH and deploy node app
  #     uses: garygrossgarten/github-action-ssh@release
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USERNAME }}
  #       password: ${{ secrets.PASSWORD }}
  #       script: |
  #         cd ~/api
  #         git pull origin master
  #         npm install --production
  #         pm2 restart app.js
