name: CI / CD

on:
  push:
    branches: [main]
    paths:
    - 'front/**'
 
env:
  REGISTRY: "registry.digitalocean.com/develop-project"
  IMAGE_NAME: "app"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2
      
    - name: Build container image
      run: docker build -t app .
      working-directory: ./front

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
      
    - name: Tag image 
      run: docker tag $(echo $IMAGE_NAME) $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
      working-directory: ./api

    - name: Push image to DigitalOcean Container Registry
      run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
      working-directory: ./api

  deploy:
    needs: [build_and_push]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          rm -rf proyecto-2
          git clone https://github.com/portilloromano/proyecto-2.git
          cd github-actions-deploy-compose-project
          docker stop app
          docker rm app
          docker-compose up -d app
