name: CI / CD

on:
  push:
    branches: [main]
    paths:
    - 'front/**'
 
env:
  REGISTRY: "registry.digitalocean.com/develop-project"
  IMAGE_NAME: "app"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
      working-directory: ./front
      env:
        CI: true

  build_and_push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2
      
    - name: Build container image
      run: docker build -t api .
      working-directory: ./front

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
      
    - name: Tag image 
      run: docker tag $(echo $IMAGE_NAME) $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
      working-directory: ./api

    - name: Push image to DigitalOcean Container Registry
      run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
      working-directory: ./api

  deploy:
    needs: [build_and_push]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          rm -rf proyecto-2
          git clone https://github.com/portilloromano/proyecto-2.git
          cd github-actions-deploy-compose-project
          docker stop app
          docker rm app
          docker-compose up -d app